### ISSUE TITLE
Question: does it work with mariadb?

### ISSUE THREAD

**Issue by dazinator** [angelo-v/wordpress-backup-quickstart#2]
Hi,

I am using MariaDb instead of Mysql container for my WordPress db. I know the two are largely compatible.

My question: do you know if this is supported?

**Comment by angelo-v** [comment]
Sorry I do not know and have not tested it, but you can give it a try

**Comment by dazinator** [comment]
I got this working on docker swarm and mariadb - the only thing I wasn't able to solve was, being able to pass the database root / user passwords as files which I raised this issue for: https://github.com/angelo-v/wordpress-backup/issues/35

1. I had to to give my service an alias of `mysql` so that the backup service could still see it on the network:

e.g

```
services:
  db:
    image: mariadb
    #restart: always
    networks:   
      maria-db:
        aliases: # https://github.com/moby/moby/issues/38066
          - mysql # required as backup container makes call on this hostname
          
# omitted for brevity
```

> Finished: SUCCESS
